[package]
name = "send-with-sendgrid-and-rust"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Setter"]

[dependencies]
error-chain = "0.12.4"
reqwest = { varsion = "0.11.11", features = ["json", "blocking"] }
serde_json = "1.0.82"
